# 1. Gunakan image dasar PHP resmi dengan Apache
FROM php:8.4-apache

# 2. Install dependencies sistem, Python 3, dan virtual environment
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*
# Install ekstensi database untuk Laravel
RUN docker-php-ext-install pdo pdo_mysql

# 3. Aktifkan modul mod_rewrite bawaan Apache untuk routing Laravel
RUN a2enmod rewrite

# 4. Arahkan DocumentRoot Apache langsung ke folder /public milik Laravel
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# 5. Install Composer terbaru secara otomatis
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 6. Set folder kerja di dalam container
WORKDIR /var/www/html

# 7. Salin semua file proyek ke dalam container
COPY . .

# 8. Setup Python Virtual Environment & Install paket dari requirements.txt
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# 9. Install PHP dependencies via Composer
# Paksa Laravel pakai mode file agar tidak mencari tabel database saat proses build
ENV CACHE_STORE=file
ENV CACHE_DRIVER=file
RUN composer install --no-dev --optimize-autoloader

# 10. Atur hak akses folder storage dan cache Laravel agar tidak Error 500
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# 11. Berikan izin eksekusi untuk script start.sh
RUN chmod +x start.sh

# 12. Eksekusi script peluncur saat container dinyalakan
CMD ["./start.sh"]