# Menggunakan image dasar yang punya PHP dan Apache
FROM webdevops/php-apache:8.2

# Install Python dan pip
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# Set up virtual environment untuk Python
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy semua file ke dalam server
COPY . /app
WORKDIR /app

# Install dependency Python
RUN pip install -r requirements.txt

# Install dependency PHP/Laravel
RUN composer install

# Expose port
EXPOSE 80